---
- hosts: centos
  vars:
    training:
      topic: ansible
      tariner: sathish
      mode: online
  tasks:
  - name: print dict varaiable
    debug:
      msg: "key is {{ item.key }} and value is {{ item.value }}"
    with_dict: "{{ training }}"
