---
- hosts: centos
  become: yes
  tasks:
  - name: install mariadb server
    yum:
      name: mariadb-server
      state: latest
    tags:
    - install
  - name: start mariadb
    service:
      name: mariadb
      state: started
    tags:
    - start
