---
- hosts: win
  tasks:
  - name: download apache
    win_get_url:
      url: http://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: C:\training\httpd-2.2.25-win32-x86-no_ssl.msi
  - name: Install MSI package
    win_package:
      path: C:\training\httpd-2.2.25-win32-x86-no_ssl.msi
      state: present
